########################################################################
# Code listing from "Advanced Linux Programming," by CodeSourcery LLC  #
# Copyright (C) 2001 by New Riders Publishing                          #
# See COPYRIGHT for license information.                               #
########################################################################
# Makefile is modfied by Irene Huang on Sep. 20th 2011
########################################################################

OBJECTS		= 
LIBRARIES	=
PROGRAMS	= fork-exec 


.PHONY:         all clean

# Default target: build everything.
all: $(PROGRAMS)

fork-exec: fork-exec.c 

# Clean up build products.
clean:
	rm -f *.o *.a $(PROGRAMS)
